"use client"

export const codeExamples = [
  [
    'import React, { useState } from "react";',
    'import { BrowserRouter as Router, Route, Routes, Link } from "react-router-dom";',
    'import Home from "./pages/Home";',
    'import Videos from "./pages/Videos";',
    'import Pictures from "./pages/Pictures";',
    'import About from "./pages/About";',
    'import Schedule from "./pages/Schedule";',
    'import Contact from "./pages/Contact";',
    'import "./App.css";',
    "",
    "function App() {",
    "  const [activeLink, setActiveLink] = useState(null);",
    "",
    "  const handleSetActive = (link) => {",
    "    setActiveLink(link);",
    "  };",
    "",
    "  return (",
    "    <Router>",
    '      <div className="App">',
    "        <nav>",
    "          <ul>",
    "            <li>",
    '              <Link to="/" onClick={() => handleSetActive("home")} className={activeLink === "home" ? "active-link" : ""}>',
    "                Home",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/videos" onClick={() => handleSetActive("videos")} className={activeLink === "videos" ? "active-link" : ""}>',
    "                Videos",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/pictures" onClick={() => handleSetActive("pictures")} className={activeLink === "pictures" ? "active-link" : ""}>',
    "                Pictures",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/schedule" onClick={() => handleSetActive("schedule")} className={activeLink === "schedule" ? "active-link" : ""}>',
    "                Schedule",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/about" onClick={() => handleSetActive("about")} className={activeLink === "about" ? "active-link" : ""}>',
    "                About",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/contact" onClick={() => handleSetActive("contact")} className={activeLink === "contact" ? "active-link" : ""}>',
    "                Contact",
    "              </Link>",
    "            </li>",
    "          </ul>",
    "        </nav>",
    "        <Routes>",
    '          <Route path="/" element={<Home />} />',
    '          <Route path="/videos" element={<Videos />} />',
    '          <Route path="/pictures" element={<Pictures />} />',
    '          <Route path="/schedule" element={<Schedule />} />',
    '          <Route path="/about" element={<About />} />',
    '          <Route path="/contact" element={<Contact />} />',
    "        </Routes>",
    "      </div>",
    "    </Router>",
    "  );",
    "}",
    "",
    "export default App;",
  ],
  [
    "import React, { useMemo } from 'react';",
    "import { SafeAreaView } from 'react-native-safe-area-context';",
    "import { useRouter } from 'expo-router';",
    "import { FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';",
    "import { ThemedText } from '@/components/themed-text';",
    "import { paintingThemes, PaintingThemeId } from '../constants/paintingThemes';",
    "",
    "type ThemeItem = { id: PaintingThemeId; colors: readonly string[] };",
    "",
    "export default function Index() {",
    "  const router = useRouter();",
    "",
    "  const data = useMemo<ThemeItem[]>(",
    "    () => Object.entries(paintingThemes).map(([id, colors]) => ({ id: id as PaintingThemeId, colors })),",
    "    []",
    "  );",
    "",
    "  const renderItem = ({ item }: { item: ThemeItem }) => {",
    "    const isHoliday = item.id === 'halloween';",
    "",
    "    const card = (",
    "      <TouchableOpacity",
    "        onPress={() => {",
    "          router.push({ pathname: '/paint' as any, params: { theme: item.id } });",
    "        }}",
    "        style={[styles.card, isHoliday && styles.holidayCard]}",
    "        activeOpacity={0.9}",
    "      >",
    "        {isHoliday && (",
    "          <View style={styles.holidayBanner}>",
    "            <Text style={styles.holidayBannerText}>Limited Holiday Theme!</Text>",
    "          </View>",
    "        )}",
    "        <ThemedText style={styles.cardTitle}>{item.id}</ThemedText>",
    "        <View style={styles.swatchRow}>",
    "          {item.colors.map((c) => (",
    "            <View key={c} style={[styles.swatch, { backgroundColor: c }]} />",
    "          ))}",
    "        </View>",
    "      </TouchableOpacity>",
    "    );",
    "",
    "    if (!isHoliday) {",
    "      return card;",
    "    }",
    "",
    "    return <View style={styles.holidayWrapper}>{card}</View>;",
    "  };",
    "",
    "  return (",
    "    <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>",
    "      <View style={styles.container}>",
    "        <ThemedText type=\"title\" style={[styles.title, styles.titleBold]}>Pawcasso</ThemedText>",
    "        <ThemedText style={styles.subtitle}>Tap a theme to start</ThemedText>",
    "",
    "        <FlatList",
    "          data={data}",
    "          keyExtractor={(item) => item.id}",
    "          renderItem={renderItem}",
    "          contentContainerStyle={styles.listContent}",
    "        />",
    "      </View>",
    "    </SafeAreaView>",
    "  );",
    "}",
  ],
]
