export const codeExamples = [
  [
    "import React, { useMemo } from 'react';",
    "import { SafeAreaView } from 'react-native-safe-area-context';",
    "import { useRouter } from 'expo-router';",
    "import { FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';",
    "import { ThemedText } from '@/components/themed-text';",
    "import { paintingThemes, PaintingThemeId } from '../constants/paintingThemes';",
    "",
    "type ThemeItem = { id: PaintingThemeId; colors: readonly string[] };",
    "",
    "export default function Index() {",
    "  const router = useRouter();",
    "",
    "  const data = useMemo<ThemeItem[]>(",
    "    () => Object.entries(paintingThemes).map(([id, colors]) => ({ id: id as PaintingThemeId, colors })),",
    "    []",
    "  );",
    "",
    "  const renderItem = ({ item }: { item: ThemeItem }) => {",
    "    const isHoliday = item.id === 'halloween';",
    "",
    "    const card = (",
    "      <TouchableOpacity",
    "        onPress={() => {",
    "          router.push({ pathname: '/paint' as any, params: { theme: item.id } });",
    "        }}",
    "        style={[styles.card, isHoliday && styles.holidayCard]}",
    "        activeOpacity={0.9}",
    "      >",
    "        {isHoliday && (",
    "          <View style={styles.holidayBanner}>",
    "            <Text style={styles.holidayBannerText}>Limited Holiday Theme!</Text>",
    "          </View>",
    "        )}",
    "        <ThemedText style={styles.cardTitle}>{item.id}</ThemedText>",
    "        <View style={styles.swatchRow}>",
    "          {item.colors.map((c) => (",
    "            <View key={c} style={[styles.swatch, { backgroundColor: c }]} />",
    "          ))}",
    "        </View>",
    "      </TouchableOpacity>",
    "    );",
    "",
    "    if (!isHoliday) {",
    "      return card;",
    "    }",
    "",
    "    return <View style={styles.holidayWrapper}>{card}</View>;",
    "  };",
    "",
    "  return (",
    "    <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}>",
    "      <View style={styles.container}>",
    "        <ThemedText type=\"title\" style={[styles.title, styles.titleBold]}>Pawcasso</ThemedText>",
    "        <ThemedText style={styles.subtitle}>Tap a theme to start</ThemedText>",
    "",
    "        <FlatList",
    "          data={data}",
    "          keyExtractor={(item) => item.id}",
    "          renderItem={renderItem}",
    "          contentContainerStyle={styles.listContent}",
    "        />",
    "      </View>",
    "    </SafeAreaView>",
    "  );",
    "}",
  ],
  [
    "import { lazy, Suspense, useEffect, useRef, useState } from 'react';",
    "import Navbar from './components/Navbar';",
    "import Hero from './components/Hero';",
    "import SectionSkeleton from './components/SectionSkeleton';",
    "import { useDeferredComponent } from './hooks/useDeferredComponent';",
    "import { useNearViewportLoad } from './hooks/useNearViewportLoad';",
    "",
    "const About = lazy(() => import('./components/About'));",
    "const Videos = lazy(() => import('./components/Videos'));",
    "const Pictures = lazy(() => import('./components/Pictures'));",
    "const Schedule = lazy(() => import('./components/Schedule'));",
    "const Contact = lazy(() => import('./components/Contact'));",
    "const Footer = lazy(() => import('./components/Footer'));",
    "",
    "function App() {",
    "  const progressBarRef = useRef(null);",
    "  const scrollPositionRef = useRef(0);",
    "  const rafRef = useRef(null);",
    "  const saveTimeoutRef = useRef(null);",
    "  const docHeightRef = useRef(0);",
    "  ",
    "  const deferredFallback = useDeferredComponent(1800);",
    "  const { shouldLoad: isNearViewport, setObserverRef: setBelowFoldSentinel } = useNearViewportLoad({",
    "    rootMargin: '0px 0px 35% 0px',",
    "    threshold: 0,",
    "  });",
    "  const shouldLoadBelowFold = deferredFallback || isNearViewport;",
    "",
    "  useEffect(() => {",
    "    const savedScrollPosition = sessionStorage.getItem('scrollPosition');",
    "    const isPageRefresh = performance.getEntriesByType('navigation')[0]?.type === 'reload';",
    "",
    "    if (savedScrollPosition && isPageRefresh) {",
    "      setTimeout(() => {",
    "        window.scrollTo(0, parseInt(savedScrollPosition, 10));",
    "      }, 100);",
    "    } else {",
    "      sessionStorage.removeItem('scrollPosition');",
    "    }",
    "",
    "    if (typeof window === 'undefined' || !progressBarRef.current) {",
    "      return undefined;",
    "    }",
    "",
    "    const updateProgress = () => {",
    "      const progress = docHeightRef.current > 0 ? scrollPositionRef.current / docHeightRef.current : 0;",
    "      if (progressBarRef.current) {",
    "        progressBarRef.current.style.setProperty('--progress', Math.min(Math.max(progress, 0), 1).toString());",
    "      }",
    "    };",
    "",
    "    const scheduleSave = () => {",
    "      if (saveTimeoutRef.current !== null) {",
    "        return;",
    "      }",
    "      saveTimeoutRef.current = window.setTimeout(() => {",
    "        sessionStorage.setItem('scrollPosition', scrollPositionRef.current.toString());",
    "        saveTimeoutRef.current = null;",
    "      }, 200);",
    "    };",
    "",
    "    const handleScroll = () => {",
    "      scrollPositionRef.current = window.scrollY;",
    "      if (!rafRef.current) {",
    "        rafRef.current = requestAnimationFrame(() => {",
    "          updateProgress();",
    "          rafRef.current = null;",
    "        });",
    "      }",
    "      scheduleSave();",
    "    };",
    "",
    "    const updateDocHeight = () => {",
    "      docHeightRef.current = document.documentElement.scrollHeight - window.innerHeight;",
    "    };",
    "",
    "    const handleResize = () => {",
    "      if (!rafRef.current) {",
    "        rafRef.current = requestAnimationFrame(() => {",
    "          docHeightRef.current = document.documentElement.scrollHeight - window.innerHeight;",
    "          updateProgress();",
    "          rafRef.current = null;",
    "        });",
    "      }",
    "    };",
    "",
    "    window.addEventListener('scroll', handleScroll, { passive: true });",
    "    window.addEventListener('resize', handleResize);",
    "    scrollPositionRef.current = window.scrollY;",
    "    updateDocHeight();",
    "    updateProgress();",
    "",
    "    const handleBeforeUnload = () => {",
    "      sessionStorage.setItem('scrollPosition', window.scrollY.toString());",
    "    };",
    "    window.addEventListener('beforeunload', handleBeforeUnload);",
    "",
    "    const revealObserver = 'IntersectionObserver' in window",
    "      ? new IntersectionObserver((entries) => {",
    "          entries.forEach((entry) => {",
    "            if (entry.isIntersecting) {",
    "              entry.target.classList.add('animate-visible');",
    "              revealObserver.unobserve(entry.target);",
    "            }",
    "          });",
    "        }, {",
    "          threshold: 0.1,",
    "          rootMargin: '0px 0px -50px 0px',",
    "        })",
    "      : null;",
    "",
    "    const registerAnimatedElements = () => {",
    "      if (typeof window === 'undefined') {",
    "        return;",
    "      }",
    "      if (!revealObserver) {",
    "        document.querySelectorAll('.animate-slide-up, .animate-fade-in').forEach((element) => {",
    "          element.classList.add('animate-visible');",
    "        });",
    "        return;",
    "      }",
    "      document.querySelectorAll('.animate-slide-up, .animate-fade-in').forEach((element) => {",
    "        if (element.dataset.observed === 'true') {",
    "          return;",
    "        }",
    "        element.dataset.observed = 'true';",
    "        revealObserver.observe(element);",
    "      });",
    "    };",
    "",
    "    registerAnimatedElements();",
    "",
    "    const mutationObserver = 'MutationObserver' in window",
    "      ? new MutationObserver(() => {",
    "          registerAnimatedElements();",
    "        })",
    "      : null;",
    "",
    "    if (mutationObserver) {",
    "      mutationObserver.observe(document.body, {",
    "        childList: true,",
    "        subtree: true,",
    "      });",
    "    }",
    "",
    "    return () => {",
    "      window.removeEventListener('scroll', handleScroll);",
    "      window.removeEventListener('resize', handleResize);",
    "      window.removeEventListener('beforeunload', handleBeforeUnload);",
    "      if (rafRef.current) {",
    "        cancelAnimationFrame(rafRef.current);",
    "      }",
    "      if (saveTimeoutRef.current) {",
    "        clearTimeout(saveTimeoutRef.current);",
    "        saveTimeoutRef.current = null;",
    "      }",
    "      if (revealObserver) {",
    "        revealObserver.disconnect();",
    "      }",
    "      if (mutationObserver) {",
    "        mutationObserver.disconnect();",
    "      }",
    "    };",
    "  }, []);",
    "",
    "  const isAdminPath = typeof window !== 'undefined' && window.location.pathname.startsWith('/admin');",
    "",
    "  if (isAdminPath) {",
    "    const AdminRoute = lazy(() => import('./features/admin/routes/AdminRoute'));",
    "    return (",
    "      <div className=\"App bg-night-sky text-moonlight overflow-x-hidden font-desert min-h-screen\">",
    "        <Suspense fallback={<div className=\"min-h-screen flex items-center justify-center\">Loading admin...</div>}>",
    "          <AdminRoute />",
    "        </Suspense>",
    "      </div>",
    "    );",
    "  }",
    "",
    "  return (",
    "    <div className=\"App bg-night-sky text-moonlight overflow-x-hidden font-desert min-h-screen\">",
    "      <div",
    "        ref={progressBarRef}",
    "        className=\"scroll-progress\"",
    "        aria-hidden=\"true\"",
    "      />",
    "      <Navbar />",
    "      <Hero />",
    "      <div ref={setBelowFoldSentinel} aria-hidden=\"true\" className=\"h-px w-full opacity-0 pointer-events-none\" />",
    "      {shouldLoadBelowFold && (",
    "        <>",
    "          <Suspense fallback={<SectionSkeleton sectionId=\"about\" />}>",
    "            <About />",
    "          </Suspense>",
    "          <Suspense fallback={<SectionSkeleton sectionId=\"videos\" />}>",
    "            <Videos />",
    "          </Suspense>",
    "          <Suspense fallback={<SectionSkeleton sectionId=\"pictures\" />}>",
    "            <Pictures />",
    "          </Suspense>",
    "          <Suspense fallback={<SectionSkeleton sectionId=\"schedule\" />}>",
    "            <Schedule />",
    "          </Suspense>",
    "          <Suspense fallback={<SectionSkeleton sectionId=\"contact\" />}>",
    "            <Contact />",
    "          </Suspense>",
    "          <Suspense fallback={<div className=\"min-h-[200px]\" />}>",
    "            <Footer />",
    "          </Suspense>",
    "        </>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
    "export default App;",
  ]
];
