"use client"

export const codeExamples = [
  [
    'import React, { useState } from "react";',
    'import { BrowserRouter as Router, Route, Routes, Link } from "react-router-dom";',
    'import Home from "./pages/Home";',
    'import Videos from "./pages/Videos";',
    'import Pictures from "./pages/Pictures";',
    'import About from "./pages/About";',
    'import Schedule from "./pages/Schedule";',
    'import Contact from "./pages/Contact";',
    'import "./App.css";',
    "",
    "function App() {",
    "  const [activeLink, setActiveLink] = useState(null);",
    "",
    "  const handleSetActive = (link) => {",
    "    setActiveLink(link);",
    "  };",
    "",
    "  return (",
    "    <Router>",
    '      <div className="App">',
    "        <nav>",
    "          <ul>",
    "            <li>",
    '              <Link to="/" onClick={() => handleSetActive("home")} className={activeLink === "home" ? "active-link" : ""}>',
    "                Home",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/videos" onClick={() => handleSetActive("videos")} className={activeLink === "videos" ? "active-link" : ""}>',
    "                Videos",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/pictures" onClick={() => handleSetActive("pictures")} className={activeLink === "pictures" ? "active-link" : ""}>',
    "                Pictures",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/schedule" onClick={() => handleSetActive("schedule")} className={activeLink === "schedule" ? "active-link" : ""}>',
    "                Schedule",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/about" onClick={() => handleSetActive("about")} className={activeLink === "about" ? "active-link" : ""}>',
    "                About",
    "              </Link>",
    "            </li>",
    "            <li>",
    '              <Link to="/contact" onClick={() => handleSetActive("contact")} className={activeLink === "contact" ? "active-link" : ""}>',
    "                Contact",
    "              </Link>",
    "            </li>",
    "          </ul>",
    "        </nav>",
    "        <Routes>",
    '          <Route path="/" element={<Home />} />',
    '          <Route path="/videos" element={<Videos />} />',
    '          <Route path="/pictures" element={<Pictures />} />',
    '          <Route path="/schedule" element={<Schedule />} />',
    '          <Route path="/about" element={<About />} />',
    '          <Route path="/contact" element={<Contact />} />',
    "        </Routes>",
    "      </div>",
    "    </Router>",
    "  );",
    "}",
    "",
    "export default App;",
  ],
  [
    'import { useState } from "react";',
    'import { motion } from "framer-motion";',
    'import { FaPaw, FaPalette, FaCamera, FaDownload } from "react-icons/fa";',
    'import "./index.css";',
    "",
    'const themes = ["default", "vintage", "neon", "pastel", "forest", "ocean"];',
    "",
    "export default function App() {",
    '  const [selectedTheme, setSelectedTheme] = useState("default");',
    '  const [selectedStyle, setSelectedStyle] = useState("");',
    "  const [uploadedImage, setUploadedImage] = useState(null);",
    '  const [generatedImage, setGeneratedImage] = useState("");',
    "  const [loading, setLoading] = useState(false);",
    "",
    "  const handleImageUpload = (e) => {",
    "    const file = e.target.files[0];",
    "    if (file) {",
    "      const reader = new FileReader();",
    "      reader.onloadend = () => {",
    "        setUploadedImage(reader.result);",
    "      };",
    "      reader.readAsDataURL(file);",
    "    }",
    "  };",
    "",
    "  const generateArt = async () => {",
    "    if (!uploadedImage || !selectedStyle) {",
    '      alert("Please upload an image and select a style");',
    "      return;",
    "    }",
    "",
    "    setLoading(true);",
    "    setTimeout(() => {",
    "      setGeneratedImage(uploadedImage);",
    "      setLoading(false);",
    "    }, 2000);",
    "  };",
    "",
    "  const downloadImage = () => {",
    "    if (!generatedImage) return;",
    "",
    '    const link = document.createElement("a");',
    "    link.href = generatedImage;",
    '    link.download = "pawcasso-art.png";',
    "    link.click();",
    "  };",
    "",
    "  return (",
    "    <div className={`app-container theme-${selectedTheme}`}>",
    '      <header className="header">',
    '        <motion.div initial={{ y: -50 }} animate={{ y: 0 }} className="logo">',
    '          <FaPaw className="paw-icon" />',
    "          <h1>Pawcasso</h1>",
    "        </motion.div>",
    '        <p className="tagline">Transform your pet photos into stunning artwork</p>',
    "      </header>",
    "",
    '      <main className="main-content">',
    '        <section className="upload-section">',
    "          <h2>",
    "            <FaCamera /> Upload Your Pet Photo",
    "          </h2>",
    '          <input type="file" accept="image/*" onChange={handleImageUpload} className="file-input" />',
    "          {uploadedImage && (",
    '            <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="preview">',
    '              <img src={uploadedImage || "/placeholder.svg"} alt="Uploaded pet" />',
    "            </motion.div>",
    "          )}",
    "        </section>",
    "",
    '        <section className="style-section">',
    "          <h2>",
    "            <FaPalette /> Choose Art Style",
    "          </h2>",
    '          <div className="style-grid">',
    "            {themes.map((theme) => (",
    "              <motion.button",
    "                key={theme}",
    "                whileHover={{ scale: 1.05 }}",
    "                whileTap={{ scale: 0.95 }}",
    '                className={`style-btn ${selectedStyle === theme ? "active" : ""}`}',
    "                onClick={() => setSelectedStyle(theme)}",
    "              >",
    "                {theme}",
    "              </motion.button>",
    "            ))}",
    "          </div>",
    "        </section>",
    "",
    '        <button onClick={generateArt} disabled={loading} className="generate-btn">',
    '          {loading ? "Generating..." : "Generate Art"}',
    "        </button>",
    "",
    "        {generatedImage && (",
    '          <section className="result-section">',
    "            <h2>Your Masterpiece</h2>",
    '            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="result-image">',
    '              <img src={generatedImage || "/placeholder.svg"} alt="Generated art" />',
    '              <button onClick={downloadImage} className="download-btn">',
    "                <FaDownload /> Download",
    "              </button>",
    "            </motion.div>",
    "          </section>",
    "        )}",
    "      </main>",
    "    </div>",
    "  );",
    "}",
  ],
]
